# Generated by simulation_designer prototype
# Manual review required before running.
# generated_simulation

import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent.parent
_src = _root / "src"
for p in (_src, _root):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from src.core import (
    Engine,
    Event,
    SimulationContext,
    SourceComponent,
    DelayComponent,
    TransformerComponent,
    SinkComponent,
)
from src.modules import setup_logging
from src.modules.utils import ConstantDistribution, UniformDistribution, ExponentialDistribution

def entity_source_1(ctx: SimulationContext):
    return {"name": 'entity'}

def generated_simulation(visualize: bool = False) -> Engine:
    engine = Engine(visualize=visualize, time_limit=None, output_dir='output')

    source_1 = SourceComponent('source_1', entity_source_1, interval=ConstantDistribution(1), track_state=False)
    engine.add_startup_event(Event(0, 'source_1', "Generate", {}, {}))
    delay_2 = DelayComponent('delay_2', ConstantDistribution(1), capacity=1000, track_state=False)
    sink_3 = SinkComponent('sink_3', track_state=False)

    engine.add_component(source_1)
    engine.add_component(delay_2)
    engine.add_component(sink_3)
    engine.connect(source_1, delay_2)
    engine.connect(delay_2, sink_3)

    engine.run()
    return engine


if __name__ == "__main__":
    setup_logging(log_file='sim.log', output_dir='output')
    generated_simulation(visualize=False)
